version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres-db
    ports: 
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: nest-app
    environment: 
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=true
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${DB_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports: 
      - "3000:3000"
    container_name: nest-app
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
volumes:
  pgdata:
  pgadmin-data: